//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект.windows
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autos
    {
        public int id { get; set; }
        public string NameAuto { get; set; }
        public Nullable<int> PostID { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
