//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект.windows
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Yacenko_12Entities455 : DbContext
    {
        public Yacenko_12Entities455()
            : base("name=Yacenko_12Entities455")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animals> Animals { get; set; }
        public virtual DbSet<Autos> Autos { get; set; }
        public virtual DbSet<Buyer> Buyer { get; set; }
        public virtual DbSet<Culture> Culture { get; set; }
        public virtual DbSet<Employes> Employes { get; set; }
        public virtual DbSet<Farms> Farms { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<WareHouse> WareHouse { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual ObjectResult<sp_GetSalesReport_Result> sp_GetSalesReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSalesReport_Result>("sp_GetSalesReport");
        }
    
        public virtual ObjectResult<sp_GetAutoMovementReport_Result> sp_GetAutoMovementReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAutoMovementReport_Result>("sp_GetAutoMovementReport");
        }
    }
}
