//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Проект.windows
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int id { get; set; }
        public Nullable<int> Amount { get; set; }
        public int BuyerID { get; set; }
        public string SubjectSale { get; set; }
        public Nullable<int> IDFarms { get; set; }
        public Nullable<int> QuantityAnimals { get; set; }
        public Nullable<int> IdWH { get; set; }
        public Nullable<int> QuantityCulture { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Farms Farms { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
